# Generated by Django 3.1.5 on 2021-01-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_auto_20210111_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(to='course_app.Event'),
        ),
    ]
